### ISSUE TITLE
Please remove the peer dependency on `@types/react`

### ISSUE THREAD

**Issue by nickretallack** [native-html/core#1]
React 17 ships with its own types.  This library pulls in old React types which messes it up.

**Comment by jsamr** [comment]
Hi, and thank you for your suggestion. PRs are welcome, I will not have time to work on this project for at least a few weeks, but I will gladly review PRs.

**Comment by jsamr** [comment]
@nickretallack I don't know how did you come to this conclusion, but that doesn't seem to be a fact, at least for react@17.0.2. You will notice in their package.json there is no `types` entry: https://github.com/facebook/react/blob/12adaffef7105e2714f82651ea51936c563fe15c/packages/react/package.json#L1-L40

**Comment by dhcmega** [comment]
Hi
I'm on expo SDK50 which has React 17 and I get this error too:

warning "react-native-render-html > @native-html/transient-render-engine@11.2.3" has unmet peer dependency "@types/react-native@*".
